name: 'Dependencies'

on:
  push:
    branches:
      - 'master'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.welcome=never

jobs:
  dependencies:
    name: 'Dependencies'
    runs-on: ubuntu-latest

    # The Dependency Submission API requires write permission.
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch Git tags, so that semantic version can be calculated.
          # Alternatively, run `git fetch --prune --unshallow --tags` as the
          # next step, see
          # https://github.com/actions/checkout/issues/206#issuecomment-607496604.
          fetch-depth: 0

      - name: Setup JDK 11 & Gradle
        uses: .github/java-and-gradle-setup

      - name: 'Run snapshot action'
        uses: mikepenz/gradle-dependency-submission@v0.9.1
        with:
          use-gradlew: true
          gradle-build-module: |-
            :diktat-api
            :diktat-common-test
            :diktat-ktlint-engine
            :diktat-gradle-plugin
            :diktat-maven-plugin
            :diktat-rules
            :diktat-ruleset
            :diktat-runner
            :diktat-dev-ksp
            :diktat-cli
          gradle-build-configuration: |-
            compileClasspath
          sub-module-mode: 'INDIVIDUAL'
