name: Run diKTat (snapshot)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diktat_snapshot_check:
    name: 'Check the project using diktat snapshot plugin'
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch Git tags, so that semantic version can be calculated.
          # Alternatively, run `git fetch --prune --unshallow --tags` as the
          # next step, see
          # https://github.com/actions/checkout/issues/206#issuecomment-607496604.
          fetch-depth: 0

      - name: Setup JDK 11 & Gradle
        uses: .github/java-and-gradle-setup

      - name: 'Cache ~/.konan'
        id: cache-konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}-build-java${{ matrix.java-version }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}-
            ${{ runner.os }}-konan-

      - name: 'Publish a snapshot version to local repo'
        id: generateLibsForDiktatSnapshot
        run: |
          ./gradlew \
            :generateLibsForDiktatSnapshot \
            -x detekt \
            -x test \
            -x diktatCheck

      # copied from .github/workflows/diktat.yml
      - name: Run diktatCheck mergeDiktatReports
        run: |
          ./gradlew \
            diktatCheck \
            mergeDiktatReports \
            -Pdiktat.githubActions=true \
            -Pdetekt.multiplatform.disabled=true \
            --continue \
            --build-cache \
            -PgprUser=${{ github.actor }} \
            -PgprKey=${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF report to Github
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ always() }}
        with:
          sarif_file: build/reports/diktat/diktat-merged.sarif
          # override category to have a different with release version
          category: diktat (snapshot)
      - name: Upload SARIF artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: sarif-reports
          path: "**/build/reports/diktat"
          retention-days: 1
