name: Run diKTat (release)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diktat_check:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 11 & Gradle
        uses: .github/java-and-gradle-setup
      - name: Run diktatCheck mergeDiktatReports
        run: |
          ./gradlew \
            diktatCheck \
            mergeDiktatReports \
            -Pdiktat.githubActions=true \
            -Pdetekt.multiplatform.disabled=true \
            --continue \
            --build-cache \
            -PgprUser=${{ github.actor }} \
            -PgprKey=${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF report to Github
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ always() }}
        with:
          sarif_file: build/reports/diktat/diktat-merged.sarif
      - name: Upload SARIF artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: sarif-reports
          path: "**/build/reports/diktat"
          retention-days: 1
